version: '3.8'

services:
    db:
        container_name: db
        image: postgres:13
        restart: always
        environment:
            POSTGRES_PASSWORD: passNotSecur3
            POSTGRES_DB: bookstore
        ports:
            - 15432:5432

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        depends_on:
            - db
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./:/var/www

    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/log/:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "80:80"